# Generated by Django 3.0.4 on 2020-04-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, upload_to='review/original/')),
                ('small', models.ImageField(blank=True, upload_to='review/small/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.CharField(max_length=200)),
                ('gender', models.IntegerField(null=True)),
                ('availability', models.BooleanField()),
                ('price', models.FloatField()),
                ('base_notes', models.ManyToManyField(related_name='perfumes_base', to='perfumes.Note')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Brand')),
                ('categories', models.ManyToManyField(to='perfumes.Category')),
                ('heart_notes', models.ManyToManyField(related_name='perfumes_heart', to='perfumes.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('kor_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(to='perfumes.Image')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfumes.Perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='seasons',
            field=models.ManyToManyField(to='perfumes.Season'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top_notes',
            field=models.ManyToManyField(related_name='perfumes_top', to='perfumes.Note'),
        ),
    ]
