# Generated by Django 3.0.5 on 2020-04-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='note',
            new_name='notes',
        ),
    ]