# Generated by Django 3.0.5 on 2020-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
