# Generated by Django 3.0.5 on 2020-04-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_auto_20200414_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.CharField(max_length=200),
        ),
    ]