# Generated by Django 3.0.5 on 2020-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0009_auto_20200416_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]