# Generated by Django 3.0.5 on 2020-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0011_auto_20200416_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]