# Generated by Django 3.0.5 on 2020-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0013_auto_20200416_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
