# Generated by Django 3.0.4 on 2020-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_auto_20200416_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='kor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
