# Generated by Django 3.0.4 on 2020-04-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0016_auto_20200423_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='perfumes.Category'),
        ),
    ]
