# Generated by Django 3.0.4 on 2020-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0021_auto_20200425_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, upload_to='review/original/')),
                ('small', models.ImageField(blank=True, upload_to='review/small/')),
            ],
        ),
        migrations.RemoveField(
            model_name='base64image',
            name='data',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='base64image',
            name='original',
            field=models.ImageField(blank=True, upload_to='review/original/'),
        ),
        migrations.AddField(
            model_name='base64image',
            name='small',
            field=models.ImageField(blank=True, upload_to='review/small/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(to='perfumes.Image'),
        ),
    ]
