# Generated by Django 3.0.4 on 2020-04-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0022_auto_20200426_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base64Image',
        ),
    ]
