# Generated by Django 3.0.4 on 2020-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0023_delete_base64image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='thumbnail',
            field=models.CharField(max_length=200),
        ),
    ]
