# Generated by Django 3.0.4 on 2020-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0026_auto_20200427_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='recommended',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfume',
            name='similar',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
