# Generated by Django 3.0.4 on 2020-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0028_auto_20200428_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
