version: '3'
services:
  nginx:
    image: nginx
    ports: 
        - "8000:8000"
    volumes:
      - ./:/code
      - ./config/nginx:/etc/nginx.conf.d
    depends_on: 
      - django
  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=laure_richis
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db:3306
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=laure_richis
      - DJANGO_DB_USERNAME=user
      - DJANGO_DB_PASSWORD=1
      - DJANGO_SECRET_KEY=!1rk8bbc70u81_tjqj1v)&ar=kz%kua-*l!ru851(105*&3ki&
    expose:
      - "8000"
    command:       
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 20
        python manage.py migrate --settings=laure_richis.production
        python manage.py collectstatic --settings=laure_richis.production  --noinput
        python manage.py crontab add --settings=laure_richis.base
        gunicorn laure_richis.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=laure_richis.production
    volumes:
      - ./:/code
    depends_on:
      - db