# Generated by Django 3.0.4 on 2020-04-01 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='similar_users',
            field=models.ManyToManyField(blank=True, related_name='_user_similar_users_+', through='accounts.Similarity', to=settings.AUTH_USER_MODEL),
        ),
    ]
