# Generated by Django 3.0.4 on 2020-04-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='hate_notes',
            field=models.ManyToManyField(related_name='surveys_hate', to='perfumes.Note'),
        ),
        migrations.AddField(
            model_name='survey',
            name='like_category',
            field=models.ManyToManyField(to='perfumes.Category'),
        ),
        migrations.AddField(
            model_name='survey',
            name='like_notes',
            field=models.ManyToManyField(related_name='surveys_like', to='perfumes.Note'),
        ),
        migrations.AddField(
            model_name='survey',
            name='season',
            field=models.ManyToManyField(to='perfumes.Season'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_perfumes',
            field=models.ManyToManyField(related_name='like_users', to='perfumes.Perfume'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_users', to='perfumes.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
