# Generated by Django 3.0.5 on 2020-04-16 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_auto_20200416_1320'),
        ('accounts', '0003_user_like_perfumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnd', models.IntegerField(default=0)),
                ('hate_notes', models.ManyToManyField(related_name='hate_users', to='perfumes.Note')),
                ('like_category', models.ManyToManyField(to='perfumes.Category')),
                ('like_notes', models.ManyToManyField(related_name='like_users', to='perfumes.Note')),
                ('season', models.ManyToManyField(to='perfumes.Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]