# Generated by Django 3.0.4 on 2020-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0015_note_kor_name'),
        ('accounts', '0005_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_users', to='perfumes.Review'),
        ),
    ]
