# Generated by Django 3.0.4 on 2020-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0016_auto_20200423_1527'),
        ('accounts', '0005_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_perfumes',
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_users', to='perfumes.Review'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='hate_notes',
            field=models.ManyToManyField(related_name='surveys_hate', to='perfumes.Note'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='like_notes',
            field=models.ManyToManyField(related_name='surveys_like', to='perfumes.Note'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
